<footer>
<div class="pull-right">
<img src="assets\images\litecoin.svg" width="15px" height="15px" > <a href="?p=about"> Litecoin Manager 1.4.0</a> - © 2017 - 2023
</div>
<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if($this->section === "main"){
		$section = "";
	}else{
		$section = "?p=".$this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");

  const openMobileMenu = () => {
    const x = document.getElementById("mobileLinks");
    if (x.style.display === "block") {
      x.style.display = "none";
    } else {
      x.style.display = "block";
    }
}
</script>
